# vedant990/test3/.github/workflows/use-reusable-workflow.yml
name: Use Reusable Docker Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  call-reusable-workflow:
    uses: vedant990/test1/.github/workflows/main.yml@main
    with:
      docker_repo_dev: 'testeruser99/dev'
      docker_repo_prod: 'testeruser99/prod'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
